name: Build SmartDNS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config libssl-dev cmake git wget

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'  # 或者你需要的 Node.js 版本

    - name: Compile SmartDNS
      run: |
        chmod +x package/build-pkg.sh
        ./package/build-pkg.sh --platform linux --arch arm --with-ui --static
        ls -R /tmp/smartdns-linux/

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: smartdns
        path: /tmp/smartdns-linux/
